### ISSUE TITLE
Test my data but dont looks like me QAQ

### ISSUE THREAD

**Issue by kelisiya** [NetEase-GameAI/Face2FaceRHO#1]
Great work ! But when I test my data but dont looks like me . How to solve it ?

**Comment by NetEase-GameAI** [comment]
If you use your own image as the driving image, the result will not be like yourself, only your head pose and expression will be transferred to the source image.

**Comment by kelisiya** [comment]
> If you use your own image as the driving image, the result will not be like yourself, only your head pose and expression will be transferred to the source image.

Specifically, I use another person head .mov as driven video , and I want to dirven my onw image , but it dont look like to me .

**Comment by NetEase-GameAI** [comment]
1.Check if you use the correct src_img,src_landmark and src_headpose of your own image.
2.If the expression or driving head pose are not exactly the same with your driving image, it may be partly due to the use of the DECA 3DMM fitting algorithm.

**Comment by NetEase-GameAI** [comment]
Another reason may be currently we require the input image is square.  Try to clip your image into a square image.
