### ISSUE TITLE
fitting module

### ISSUE THREAD

**Issue by charlieguo0610** [NetEase-GameAI/Face2FaceRHO#12]
Hi,
I noticed that the inputs to fitting.py are images, and I wonder if the code supports having an image for src input and a video for the driving input. Thanks in advance!

**Comment by NetEase-GameAI** [comment]
We'll add a video demo when we have time.

**Comment by charlieguo0610** [comment]
Does current released codes support video sequence as input to fitting.py?

**Comment by charlieguo0610** [comment]
Do current released codes support video sequence as input to fitting.py?

**Comment by NetEase-GameAI** [comment]
Yes, you need to manually extract each video frame and use fitting.py for each frame.
