### ISSUE TITLE
Could you please provide a video demo?

### ISSUE THREAD

**Issue by zgxiangyang** [NetEase-GameAI/Face2FaceRHO#2]
like other code did.

**Comment by NetEase-GameAI** [comment]
We'll add a video demo when we have time, maybe next month.

**Comment by davidchateau** [comment]
Hello, yeah I'd love a demo / tutorial. Can we do video reenactment just like the examples we can find on youtube when searching for "face2face"?

**Comment by NetEase-GameAI** [comment]
We haven't gotten our company’s official permission to release the 3DMM fitting code for the video demo. You can currently use DECA to fit each video frame and perform face reenactment alternatively.
