### ISSUE TITLE
Question about the face bounding box of VoxCeleb1

### ISSUE THREAD

**Issue by HowieMa** [NetEase-GameAI/Face2FaceRHO#20]
Hi,
Thanks for sharing such an amazing project! As for the pre-processing, it is said that you follow the [video-preprocessing](https://github.com/AliaksandrSiarohin/video-preprocessing) scripts. However, in their codes, they use the bounding box as shared in the [meta-csv file](https://github.com/AliaksandrSiarohin/video-preprocessing), which is different from the original bounding box from the VoxCeleb1 dataset, as discussed in [issue21](https://github.com/AliaksandrSiarohin/video-preprocessing/issues/21). 

Therefore, may I ask which bounding box you use to obtain the cropped images? 

Besides, the original VoxCeleb1 dataset contains 1k+ subjects in the training set and 40+ subjects in the testing set. 
However, the meta-file of [video-preprocessing](https://github.com/AliaksandrSiarohin/video-preprocessing) only provides 400+ subjects, which is a subset of the original VoxCeleb1 dataset. 
Thus, may I ask which dataset you used in the training examples? The dataset with 1k+ subjects or the subset from video-preprocessing? 

Looking forward to your reply. Thanks in advance!

**Comment by NetEase-GameAI** [comment]
I use videos in the [meta-csv file](https://github.com/AliaksandrSiarohin/video-preprocessing),

**Comment by HowieMa** [comment]
非常感谢您关于video选择的回复，这对我非常有帮助。
想请教一下上述的的第一个问题，您用的是哪一种bounding box 从原始视频裁剪脸部区域的呢？
1）是直接从video-preprocessing 提供的 "[vox-metadata.csv](https://github.com/AliaksandrSiarohin/video-preprocessing/blob/master/vox-metadata.csv)", 
2）还是使用的VoxCeleb1 官方提供的原始bounding box 呢？

具体来说，
VoxCeleb1 官方给的boundingbox 都是正方形的，我看您的[dataset demo](https://github.com/NetEase-GameAI/Face2FaceRHO/blob/master/trainingset/VoxCeleb/id10001%237w0IBEWc9Qw%23000993%23001143/img/150.jpg)里似乎使用的是VoxCeleb1官方的正方形框。

但是meta csv 文件里存在很多非正方形的框，如这个[issue](https://github.com/AliaksandrSiarohin/video-preprocessing/issues/21)，他们会把非正方形的框给resize 到正方形，这样就会有畸变。比如您demo 里的图，直接使用video-preprocessing 的meta.csv 就会得到这样压的非常扁的图。
![image](https://user-images.githubusercontent.com/25797674/226300700-74503e6b-bca5-4377-94b1-f339fa09ea3d.png)
所以想找您确认一下在裁剪图片的时候使用的是哪一种bounding box，谢谢！

**Comment by NetEase-GameAI** [comment]
用的是第二种，但我这边是在其给出的bounding box的基础上对其进行了修改，不是你那的那种直接缩放，而是比如原始的框左右或者上下加一些padding的方式，保证出来的都是正方形。
