### ISSUE TITLE
使用其他3D人脸模型fitting时，对应的72个landmarks如何选择？

### ISSUE THREAD

**Issue by wong00** [NetEase-GameAI/Face2FaceRHO#23]
DECA是对应FLAME人脸模型的5000多个顶点，本项目通过landmark_embedding.json 挑选出了72个关键点，而大多数人脸模型只会给68个关键点，对于BFM人脸模型，如何才能根据索引找出符合本项目的72个关键点？
多余的4个关键点如果无法获得，能否根据邻近的关键点进行线性组合得到？

**Comment by NetEase-GameAI** [comment]
换了模型的话，关键点要在你用的人脸模板上重新选择，不一定非要用72点，68点应该也可以，跟论文里给出的配置大差不差就行。

**Comment by wong00** [comment]
感谢，DECA采用的FLAME模型，但在BFM人脸模型上对应的68个关键点也是可以的，对吗?

**Comment by NetEase-GameAI** [comment]
是的

**Comment by wong00** [comment]
十分感谢！

**Comment by tunmx** [comment]
嗨您好，我想使用自己的landmark去匹配，请问你们是如何挑选72个点的，landmark_embedding.json这个文件有在项目中吗，我没有找到
