### ISSUE TITLE
关于VoxCeleb1裁剪框选择的问题

### ISSUE THREAD

**Issue by HowieMa** [NetEase-GameAI/Face2FaceRHO#24]
非常感谢您在[issue20](https://github.com/NetEase-GameAI/Face2FaceRHO/issues/20)里关于数据集大小的回复，这对我非常有帮助。但是我还有些裁剪框(bounding box)的问题没有得到您的解释。由于那个issue已经被您关闭，我只能新开一个issue，期待您的解答。

请问您用的是哪一种bounding box 从原始视频裁剪脸部区域的呢？
1）是直接从video-preprocessing 提供的 "[vox-metadata.csv](https://github.com/AliaksandrSiarohin/video-preprocessing/blob/master/vox-metadata.csv)", 
2）还是使用的VoxCeleb1 官方提供的原始bounding box 呢？

具体来说，
VoxCeleb1 官方给的boundingbox 都是正方形的，我看您的[dataset demo](https://github.com/NetEase-GameAI/Face2FaceRHO/blob/master/trainingset/VoxCeleb/id10001%237w0IBEWc9Qw%23000993%23001143/img/150.jpg)里似乎使用的是VoxCeleb1官方的正方形框。

但是meta csv 文件里存在很多非正方形的框，如这个[issue](https://github.com/AliaksandrSiarohin/video-preprocessing/issues/21)，他们会把非正方形的框给resize 到正方形，这样就会有畸变。比如您demo 里的图，直接使用video-preprocessing 的meta.csv 就会得到这样压的非常扁的图。
![image](https://user-images.githubusercontent.com/25797674/226300700-74503e6b-bca5-4377-94b1-f339fa09ea3d.png)
所以想找您确认一下在裁剪图片的时候使用的是哪一种bounding box，谢谢！

**Comment by NetEase-GameAI** [comment]
用的是第二种，但我这边是在其给出的bounding box的基础上对其进行了修改，不是你那的那种直接缩放，而是比如原始的框左右或者上下加一些padding的方式，保证出来的都是正方形。

**Comment by HowieMa** [comment]
明白了，非常感谢您的回复！
