### ISSUE TITLE
虽然有些可以看看的结果，但loss 曲线不太正常，特别是g_loss和d_loss，请教一下

### ISSUE THREAD

**Issue by pocketvision** [NetEase-GameAI/Face2FaceRHO#25]
![res_512_3](https://user-images.githubusercontent.com/20749514/226538137-c5b1985b-e823-4069-84bf-6b1bc1cd0ec6.png)
请教一下这样的loss曲线是否正常，感觉判别器太强了，起不到指导监督作用，可以看看作者的loss曲线吗？
我用自己的三维模型，训练的结果：
源图：
![1563](https://user-images.githubusercontent.com/20749514/226538674-19517a2e-3377-440f-8b5c-5880615a8c0a.jpg)
驱动图：
![5221](https://user-images.githubusercontent.com/20749514/226538685-5b040808-eb7b-44a2-a99e-635660fb9971.jpg)
结果：
![result_0](https://user-images.githubusercontent.com/20749514/226538737-e6dd1e4a-d191-4d89-959c-5b2d1c5ed71c.png)

**Comment by NetEase-GameAI** [comment]
差不多是你这样吧 我这边其实gan loss加的比较小的 起主要作用的还是其他的loss

**Comment by pocketvision** [comment]
@NetEase-GameAI 好的，再请教个问题，这些loss之间的平衡，感觉差异挺大的，需要维持现有的量级吗？平衡成相同的量级可行吗？

**Comment by NetEase-GameAI** [comment]
应该不行 reconstruction要占主要的

**Comment by pocketvision** [comment]
@NetEase-GameAI 感谢回复，还想请教个问题：motion_net和SPADE里面的卷积都替换成mobilenet_v2中的InvertedResidual，对效果影响大吗？现有模型是否还有比较大的压缩空间？

**Comment by NetEase-GameAI** [comment]
跟你具体应用有关，如果对质量要求不太高的情况下，应该还有优化空间吧。我测试下来，再当前框架下，不太可能再大幅压缩了。

**Comment by pocketvision** [comment]
@NetEase-GameAI 你好，想和大佬交流一下我目前遇到几个问题：a、图片驱动图片还可以（相似度还在提升），但用视频人脸驱动图片人脸的结果，背景动得厉害，如下5所示，可否交流一下如何提升驱动结果的真实感？特别是背景抖动问题，还是说只能通过分割去规避类似问题？b、生成结果在边界处会有明显痕迹，如高亮，或异常的颜色。c、当驱动人脸角度【pitch, yaw, roll】变化比较大时，生成得不理想，请问大佬在做这个任务时，是否会对样本对进行对齐，校准？（校准更容易学习，但为了保证背景不动，我目前不做校准，保留了样本对之间原有的平移旋转和缩放，但模型似乎难以学到对背景的补齐能力（如impainting））
1、原始图片人脸：
![source](https://user-images.githubusercontent.com/20749514/234226074-7cfd1061-7fc8-4549-8247-9ab5d7edfc24.jpg)
2、驱动图片人脸：
![driving](https://user-images.githubusercontent.com/20749514/234226134-c8e2bdb7-0a57-43bf-9619-d880b307ca58.jpg)
3、由2驱动1，生成的图片人脸：
![res](https://user-images.githubusercontent.com/20749514/234226317-39cb547d-c8cb-464f-b283-9e5349e56d65.jpg)
4、驱动视频人脸：
https://user-images.githubusercontent.com/20749514/234226701-88c57755-b7d5-4e7a-a952-53a6d3b188d4.mp4
5、由4驱动1，生成的视频人脸：
https://user-images.githubusercontent.com/20749514/234226827-62e41eba-c2a8-4bb3-86b2-d3a9445ffc94.mp4

**Comment by daikankan** [comment]
5、由4驱动1，生成的视频人脸（上面好像没传成功）：
https://user-images.githubusercontent.com/20749514/234230509-ea4e1997-2950-4223-8b1b-bf71e6fece9d.mp4

**Comment by wong00** [comment]
> @NetEase-GameAI 你好，想和大佬交流一下我目前遇到几个问题：a、图片驱动图片还可以（相似度还在提升），但用视频人脸驱动图片人脸的结果，背景动得厉害，如下5所示，可否交流一下如何提升驱动结果的真实感？特别是背景抖动问题，还是说只能通过分割去规避类似问题？b、生成结果在边界处会有明显痕迹，如高亮，或异常的颜色。c、当驱动人脸角度【pitch, yaw, roll】变化比较大时，生成得不理想，请问大佬在做这个任务时，是否会对样本对进行对齐，校准？（校准更容易学习，但为了保证背景不动，我目前不做校准，保留了样本对之间原有的平移旋转和缩放，但模型似乎难以学到对背景的补齐能力（如impainting）） 1、原始图片人脸： ![source](https://user-images.githubusercontent.com/20749514/234226074-7cfd1061-7fc8-4549-8247-9ab5d7edfc24.jpg) 2、驱动图片人脸： ![driving](https://user-images.githubusercontent.com/20749514/234226134-c8e2bdb7-0a57-43bf-9619-d880b307ca58.jpg) 3、由2驱动1，生成的图片人脸： ![res](https://user-images.githubusercontent.com/20749514/234226317-39cb547d-c8cb-464f-b283-9e5349e56d65.jpg) 4、驱动视频人脸： https://user-images.githubusercontent.com/20749514/234226701-88c57755-b7d5-4e7a-a952-53a6d3b188d4.mp4 5、由4驱动1，生成的视频人脸： https://user-images.githubusercontent.com/20749514/234226827-62e41eba-c2a8-4bb3-86b2-d3a9445ffc94.mp4

问题一好像是因为 如果你使用的3DMM模型是针对单帧图像的话就会存在抖动，可能基于视频序列的3DMM模型的效果会更好。
另外想问您，训练的时候是只训练reenact部分，fitting部分是冻结参数的嘛？

**Comment by pocketvision** [comment]
@wong00 全部重训的，我的驱动因子不一样了（作者是基于自己厂的3DMM模型，但他们厂应该不同意开源的），我只能基于自有的资源来构建，所以重写了很多模块了

**Comment by wong00** [comment]
> @wong00 全部重训的，我的驱动因子不一样了（作者是基于自己厂的3DMM模型，但他们厂应该不同意开源的），我只能基于自有的资源来构建，所以重写了很多模块了
感谢。
请问您数据集预处理了多久？ 另外，关键点和头部姿态都是提前生成好，还是在训练的时候边生成，边渲染呢？

**Comment by wong00** [comment]
> @wong00 全部重训的，我的驱动因子不一样了（作者是基于自己厂的3DMM模型，但他们厂应该不同意开源的），我只能基于自有的资源来构建，所以重写了很多模块了

感谢。
请问您数据集预处理了多久？ 另外，关键点和头部姿态都是提前生成好，还是在训练的时候边生成，边渲染呢？

**Comment by daikankan** [comment]
@NetEase-GameAI 发现使用https://github.com/alibaba/MNN（2.5.0）进行推理结果与torch版本不一致，mnn结果有明显瑕疵，不知道是不是mnn对于FOMM模型的支持有问题，还是转模型前需要做什么其他处理，主要问题猜测可能在render模型的grid_sample和deform模块，不知道您是怎么成功转mnn模型，并得到正确的结果的？因为我用您的原版模型转mnn没有成功，以下是我训练的模型的torch的运算结果，无明显瑕疵：
![source_driving](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/832decad-b074-426c-ad68-cf983ad96679)

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/2da9a1b0-9aa4-40b4-bbc5-19626faef778

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/b865865d-b8a5-4ca1-aa38-cc6366dc7370

自己的模型转成功了，但运算结果有问题，效果如下：

![res](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/8e81f678-d070-4f07-86f0-304181869392)

请问 @NetEase-GameAI 写sdk的时候使用mnn没有遇到类似问题吗？

**Comment by pocketvision** [comment]
大家是不是都去做 diffusion model 了？ 其实这个也挺有意思的，目前的效果：

源人脸：
![source](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/c22fa2d8-16c7-4b53-8db6-fe35a21ea4ed)

驱动源（图片+蚂蚁呀嘿视频+talking视频）：
![driving](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/a313faa4-b3d6-4864-ab50-2a5b35dd644d)

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/8652fbbe-f82e-4b97-a709-b8025ccdf769

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/116d8496-5bda-4244-b065-bed03088f5b3

生成效果：
![res_512](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/2fff2afa-72dd-454f-8466-e84b9e83a423)

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/dcc82667-73b0-4513-8a67-1582c52e517a

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/bbb88b2f-73a0-4145-b208-c154453ad71f

原作者效果：
![result](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/7b7fcbea-d459-427b-982b-473ed508bfc1)
可能作者用了他们比较小的三维模型，精准度好像还不太够（DECA就更差了），如下：
![result](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/8a2582e7-4348-46d6-bd71-902686f97275)
如果作者能放一些视频效果出来就好了，探讨一下这类FOMM方法的上限究竟能达到怎样的效果，不过个人感觉三维模型好像很难把五官关键点拟合得很准，但是可以保证人脸shape。

**Comment by wong00** [comment]
> 

你上传的这几个视频有几个看不了

**Comment by wong00** [comment]
> 大家是不是都去做 diffusion model 了？ 其实这个也挺有意思的，目前的效果：
> 
> 源人脸： ![source](https://user-images.githubusercontent.com/20749514/242184815-c22fa2d8-16c7-4b53-8db6-fe35a21ea4ed.jpg)
> 
> 驱动源（图片+蚂蚁呀嘿视频+talking视频）： ![driving](https://user-images.githubusercontent.com/20749514/242185568-a313faa4-b3d6-4864-ab50-2a5b35dd644d.jpg)
> 
>  myyh.mp4 
>  m_1.mp4 
> 生成效果： ![res](https://user-images.githubusercontent.com/20749514/242813545-df17f9a7-624b-4f4c-a5ec-1a36c96878fd.png)
> 
>  source_myyh.mp4 
>  source_m_1.mp4

你上传的这几个视频有几个看不了

**Comment by pocketvision** [comment]
@wong00 
wget https://user-images.githubusercontent.com/20749514/245128317-bbb88b2f-73a0-4145-b208-c154453ad71f.mp4
wget https://user-images.githubusercontent.com/20749514/245128348-dcc82667-73b0-4513-8a67-1582c52e517a.mp4

**Comment by wong00** [comment]
> @wong00 wget https://user-images.githubusercontent.com/20749514/245128317-bbb88b2f-73a0-4145-b208-c154453ad71f.mp4 wget https://user-images.githubusercontent.com/20749514/245128348-dcc82667-73b0-4513-8a67-1582c52e517a.mp4

好像驱动效果还可以 但背景怎么抖动这么厉害 是直接拼接回原图的吗

**Comment by wong00** [comment]
@daikankan 请问您训练用了几张卡 大概训了多久啊  用的是全部数据吗

**Comment by wong00** [comment]
@daikankan 请问你在训练的时候可视化结果正常吗？ 目前训练至15个epoch 结果是这样
![Snipaste_2023-06-19_23-01-22](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/46165993/ed44ff88-a346-4ebf-83e3-f46ed5b67f86)

**Comment by QuantJia** [comment]
> 大家是不是都去做 diffusion model 了？ 其实这个也挺有意思的，目前的效果：
> 
> 源人脸： ![source](https://user-images.githubusercontent.com/20749514/242184815-c22fa2d8-16c7-4b53-8db6-fe35a21ea4ed.jpg)
> 
> 驱动源（图片+蚂蚁呀嘿视频+talking视频）： ![driving](https://user-images.githubusercontent.com/20749514/242185568-a313faa4-b3d6-4864-ab50-2a5b35dd644d.jpg)
> 
>  myyh.mp4 
>  m_1.mp4 
> 生成效果： ![res_512](https://user-images.githubusercontent.com/20749514/245128120-2fff2afa-72dd-454f-8466-e84b9e83a423.png)
> 
>  source_myyh.mp4 
>  source_m_1.mp4 
> 原作者效果： ![result](https://user-images.githubusercontent.com/20749514/245128693-7b7fcbea-d459-427b-982b-473ed508bfc1.png) 可能作者用了他们比较小的三维模型，精准度好像还不太够（DECA就更差了），如下： ![result](https://user-images.githubusercontent.com/20749514/245130313-8a2582e7-4348-46d6-bd71-902686f97275.png) 如果作者能放一些视频效果出来就好了，探讨一下这类FOMM方法的上限究竟能达到怎样的效果，不过个人感觉三维模型好像很难把五官关键点拟合得很准，但是可以保证人脸shape。

m_1 效果不错啊, 是生成的脖子以上吗

**Comment by pocketvision** [comment]
给大家看看最新的效果，感觉快到极限了> <，除非有更好的数据集，更强大的机器来训大模型，这类方法感觉对于大角度还是容易变糊（我指直接融合，不依赖分割），牙齿不太好监督：

![mnls](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/2f4e7d42-1286-477b-aa9e-8ab3bb6787f7)

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/a0778b34-86e6-4a4a-a8ae-3c242dfbb401


https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/3320f170-25b9-40d0-9b28-1424217f135f

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/9be3bdf0-df06-4090-b04f-2d7124b699e4

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/0123a1fc-9fa9-4e2f-8398-46d925b6cb18


https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/5f50301d-67a2-42ab-83fc-9b0c2a1bc148

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/f5f3b6cc-8220-4011-add9-52205eab4ca6

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/b0e14fca-c034-4521-92f0-7cf3af8cb504


其中后二个驱动视频：

https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/39d7cc28-810d-4605-854f-31cd917d390e

![0](https://github.com/NetEase-GameAI/Face2FaceRHO/assets/20749514/e2e40cc8-889d-45e1-be63-eb90ef738363)


不知道你们有没有尝试过类似 https://github.com/NVlabs/face-vid2vid 的方法，不知道会不会有质的提升？
