### ISSUE TITLE
hello, is your paper released in arxiv?

### ISSUE THREAD

**Issue by utiuyru** [NetEase-GameAI/Face2FaceRHO#4]
sorry I have not find your paper 'Real-Time High-Resolution One-Shot Face Reenactment', could you give me a url or your paper? 
Thanks a lot

**Comment by NetEase-GameAI** [comment]
We haven't released in arxiv. You can download the paper from this repository. The URL is https://github.com/NetEase-GameAI/Face2FaceRHO/blob/master/paper.pdf.
