### ISSUE TITLE
link of train dataset

### ISSUE THREAD

**Issue by starhiking** [NetEase-GameAI/Face2FaceRHO#7]
Nice Work it is!

I cannot download the dataset when press the download button in the [website](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/#portfolio).
Could you please provide the direct super link of the  downloaded dataset?

**Comment by NetEase-GameAI** [comment]
Please follow the instruction from https://github.com/AliaksandrSiarohin/video-preprocessing as we did to download Voxceleb.
